name: CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && github.ref == 'refs/heads/main'"
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install
        working-directory: functions
        run: npm install
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_ACCOUNT_CREDENTIALS }}
      - name: Deploy
        run: npx firebase-tools deploy --only functions
